### ISSUE TITLE
Questions: naming decisions

### ISSUE THREAD

**Issue by aminalhazwani** [caesarsol/postcss-fuss#1]
I was wondering why you chose to place `c-` in front of the color class name. I believe it can be omitted, what do you think? Also, have you looked at [this discussion](https://github.com/tachyons-css/tachyons/issues/216#issuecomment-233793808) about single hyphens vs double hyphens in class names?

**Comment by caesarsol** [comment]
Hola amin!
The main target of this project is to enable to create a collection of functions that can be used to build a system of functional CSS classes. So the given class names are just an example.

However, the colors convention we're currently following is to use the name of the color as given by [Sip](http://sipapp.io/) as the class name, and that is a word which sometimes is an bovious color, like `dodger-blue`, but sometimes is a non-obvious color name, as `chinook` or `arapawa` 😄

**Comment by caesarsol** [comment]
As for the double hypen, your reference is quite useful.

**Comment by caesarsol** [comment]
The big question is whether we want compatibility with `tachyons` format, or not?

**Comment by aminalhazwani** [comment]
I believe that Tachyons CSS is one of the most used functional CSS frameworks right now. IMHO choosing its format as default could potentially attract more people to use the plugin (and moreover a lot of tinkering has been done about of class-naming). With such approach FUSS would potentially output code which is more familiar to most of _functional_ coders.
